# -*- coding: utf-8 -*-
"""EjercicioRegression2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17n4Y_wtlrvW4uCPjCZ9csKbVbaJK6JVB

#Salaries

Dataset and process adapted from:  [Hands-On Machine Learning with Scikit-Learn and Tensor Flow](https://www.amazon.com/Hands-Machine-Learning-Scikit-Learn-TensorFlow/dp/1491962291)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

import timeit

df = pd.read_csv("https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv", delimiter=',')

df.head()

df.info()

df.describe()

df.hist(bins=50, figsize=(10,10))

"""Median Income until 15?
Income capped at 15 for higher incomes and 0.5 for lower median incomes.
Median Hause value and age
"""

from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.2, random_state=70)

"""## Explore and visualize training set"""

housing = train.copy()

housing.plot(kind="scatter",x="longitude",y="latitude")

housing.plot(kind="scatter",x="longitude",y="latitude", alpha=0.1)

housing.plot(kind="scatter",x="longitude",y="latitude",c="median_house_value",colormap='jet',alpha=0.2, figsize=(10,10),s=housing["population"]/100)

plt.show()

"""What else can we learn from the data? Scatter plots? Scatter matrix? distribution?"""

#Insert code
#ax=pd.plotting.scatter_matrix(housing,figsize=(15, 15),c=list(housing['hosing_median_value'].cat.codes))